[cpu]
[cpu.cores.core0]
online = true
min_freq = 2000000   # 2.0 GHz
max_freq = 3000000   # 3.0 GHz

[cpu.cores.core1]
online = true
min_freq = 1800000
max_freq = 2500000

[gpu]
min_freq = 500       # 500 MHz
max_freq = 1200      # 1.2 GHz