[cpu.big]
min_freq = 1300000
max_freq = 3050000
model = "sugov_ext"

[cpu.middle]
min_freq = 400000
max_freq = 2850000
model = "sugov_ext"

[cpu.small]
min_freq = 200000
max_freq = 1800000
model = "sugov_ext"