[default]
[default.cpu]
[default.cpu.cores.core0]
online = true
min_freq = 1000000
max_freq = 2000000

[default.cpu.cores.core1]
online = false
min_freq = 800000
max_freq = 1800000

[default.cpu.cores.core2]
online = false
min_freq = 800000
max_freq = 1800000

[default.cpu.cores.core3]
online = false
min_freq = 800000
max_freq = 1800000

[default.cpu.cores.core4]
online = false
min_freq = 800000
max_freq = 1800000

[default.cpu.cores.core5]
online = false
min_freq = 800000
max_freq = 1800000

[default.cpu.cores.core6]
online = false
min_freq = 800000
max_freq = 1800000

[default.cpu.cores.core7]
online = false
min_freq = 800000
max_freq = 1800000

[default.gpu]
min_freq = 300
max_freq = 800

[app]
"com.example.game" = "config/com.example.game.toml"
"com.example.browser" = "config/com.example.browser.toml"