[default.cpu.big]
min_freq = 1000  # 示例值，大核最小频率
max_freq = 2000  # 示例值，大核最大频率

[default.cpu.middle]
min_freq = 800   # 示例值，中核最小频率
max_freq = 1800  # 示例值，中核最大频率

[default.cpu.small]
min_freq = 500   # 示例值，小核最小频率
max_freq = 1500  # 示例值，小核最大频率

[app]
# 示例键值对（根据 HashMap<String, String> 结构）
key1 = "value1"
key2 = "value2"